version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: sm_timer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
